window.siteData = {
    categories: [
        { id: 'power-tools', slug: 'power-tools', name: 'All Power Tools', desc: 'Drills, saws, grinders', img: 'powertools.png' },
        { id: 'bosch-tools', slug: 'bosch', name: 'Bosch Power Tools', desc: 'Professional heavy-duty tools', img: 'GBH 2-26.png' },
        { id: 'cement', slug: 'cement', name: 'Cement', desc: 'OPC 43, OPC 53', img: 'assets/cement.PNG' },
        { id: 'construction-chemicals', slug: 'construction-chemicals', name: 'Construction Chemicals', desc: 'Admixtures, repair mortars', img: 'Technical & Concrete Repair.png' },
        { id: 'dewalt-tools', slug: 'dewalt', name: 'DeWalt Power Tools', desc: 'Guaranteed tough power tools', img: 'DEWALT DCD776S2-B5 18V XR LI-ION 13MM COMPACT HAMMER DRILL DRIVER.png' },
        { id: 'electrical', slug: 'electrical', name: 'Electrical Products', desc: 'Switches, wiring, fixtures', img: 'assets/electrical-products.PNG' },
        { id: 'faucets', slug: 'faucets', name: 'Faucets & Mixers', desc: 'Grohe mixers, shattafs', img: 'faucets.jpeg' },
        { id: 'fischer-products', slug: 'fischer', name: 'Fischer Fixings', desc: 'Anchors and fixings', img: 'Fischer Universal Injection Mortar Chemical Anchor FIS VS 300T.png' },
        { id: 'gypsum', slug: 'gypsum', name: 'Gypsum Products', desc: 'Gypsum boards, tiles', img: 'gypsum board.png' },
        { id: 'hardware-tools', slug: 'hardware-tools', name: 'Hardware & Tools', desc: 'Hand tools, accessories', img: 'assets/hardwaretools.png' },
        { id: 'mapei-products', slug: 'mapei', name: 'Mapei Construction Chemicals', desc: 'Premium adhesives and primers', img: 'Mapei Primer G.png' },
        { id: 'paints-coatings', slug: 'paints-coatings', name: 'Paints & Protective Coatings', desc: 'Jotun fenomastic, woodshield', img: 'fenomastic.PNG' },
        { id: 'plumbing', slug: 'plumbing', name: 'Plumbing Products', desc: 'Pipes, fittings, valves', img: 'assets/plumbing.PNG' },
        { id: 'plywood', slug: 'plywood', name: 'Plywood', desc: 'Marine plywood, MDF', img: 'Commercial Plywood.png' },
        { id: 'polythene', slug: 'polythene', name: 'Polythene Sheets', desc: 'Protection rolls', img: 'polythene1.png' },
        { id: 'safety', slug: 'safety', name: 'Safety Gear', desc: 'Helmets, shoes, protection', img: 'safety shoes.png' },
        { id: 'tapes', slug: 'tapes', name: 'Tapes', desc: 'Masking, duct, double sided', img: 'double sided masking tape.png' },
        { id: 'tile-adhesives', slug: 'tile-adhesives', name: 'Tile Adhesives & Glue', desc: 'Mapei keraflex, grouts', img: 'Mapei Keraflex.png' },
        { id: 'waterproofing', slug: 'waterproofing', name: 'Waterproofing', desc: 'Bituminous membranes', img: 'Bituminous Membran.png' }
    ],
    brands: [
        { name: 'Brand 3', img: 'assets/b1.png', verified: true },
        { name: 'Brand 4', img: 'assets/b2.png', verified: true },
        { name: 'Brand 5', img: 'assets/b3.png', verified: true },
        { name: 'Brand 6', img: 'assets/b4.png', verified: true },
        { name: 'Brand 7', img: 'assets/b5.png', verified: true },
        { name: 'Brand 8', img: 'assets/b6.png', verified: true },
        { name: 'Brand 9', img: 'assets/b7.png', verified: true },
        { name: 'Brand 10', img: 'assets/b8.png', verified: true },
        { name: 'Brand 11', img: 'assets/b9.png', verified: true },
        { name: 'Brand 12', img: 'assets/b10.png', verified: true },
        { name: 'Brand 13', img: 'assets/b11.png', verified: true },
        { name: 'Brand 14', img: 'assets/b12.png', verified: true },
        { name: 'Brand 15', img: 'assets/b13.png', verified: true },
        { name: 'Brand 16', img: 'assets/b14.png', verified: true },
        { name: 'Brand 17', img: 'assets/b15.png', verified: true },
        { name: 'Brand 18', img: 'assets/b16.png', verified: true },
        { name: 'Brand 19', img: 'assets/b17.png', verified: true },
        { name: 'Brand 20', img: 'assets/b18.png', verified: true },
        { name: 'Brand 21', img: 'assets/b19.png', verified: true },
        { name: 'Brand 22', img: 'assets/b20.png', verified: true },
        { name: 'Brand 23', img: 'assets/b21.png', verified: true },
        { name: 'Brand 24', img: 'assets/b22.png', verified: true },
        { name: 'Brand 25', img: 'assets/b23.png', verified: true },
        { name: 'Brand 26', img: 'assets/b24.png', verified: true },
        { name: 'Brand 27', img: 'assets/b25.png', verified: true },
        { name: 'Brand 28', img: 'assets/b26.png', verified: true },
        { name: 'Brand 29', img: 'assets/b27.png', verified: true },
        { name: 'Brand 30', img: 'assets/b28.png', verified: true },
        { name: 'Brand 31', img: 'assets/b29.png', verified: true },
        { name: 'Brand 32', img: 'assets/b30.png', verified: true },
        { name: 'Brand 33', img: 'assets/b31.png', verified: true },
        { name: 'Brand 34', img: 'assets/b32.png', verified: true },
        { name: 'Brand 35', img: 'assets/b34.png', verified: true },
        { name: 'Brand 36', img: 'assets/b35.png', verified: true },
        { name: 'Brand 37', img: 'assets/b37.png', verified: true },
        { name: 'Brand 38', img: 'assets/b38.png', verified: true },
        { name: 'Brand 39', img: 'assets/b39.png', verified: true },
        { name: 'Brand 40', img: 'assets/b40.png', verified: true },
        { name: 'Brand 41', img: 'assets/b41.png', verified: true }
    ]
};
